"""ulid to id

Revision ID: 0343e864391f
Revises: fd394f160c79
Create Date: 2022-02-21 11:18:58.819304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import VARCHAR
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0343e864391f"
down_revision = "fd394f160c79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction_communications",
        "ulid",
        new_column_name="id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    op.alter_column(
        "transactions",
        "ulid",
        new_column_name="id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction_communications",
        "id",
        new_column_name="ulid",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    op.alter_column(
        "transactions",
        "id",
        new_column_name="ulid",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    # ### end Alembic commands ###
