"""fix data type of api_status

Revision ID: 09dd15f01e87
Revises: e0e1f1557ff1
Create Date: 2022-09-29 09:48:31.376829

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09dd15f01e87'
down_revision = 'e0e1f1557ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund_transactions', 'api_status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refund_transactions', 'api_status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
