"""dispute

Revision ID: 1530c5d96a01
Revises: 38f46ae7c19c
Create Date: 2023-02-23 10:30:12.380849

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1530c5d96a01'
down_revision = '38f46ae7c19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_communications', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('now()'), nullable=True
               )
    op.alter_column('transaction_communications', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
