"""make pid in analytics unique

Revision ID: 1712cc0ad50e
Revises: 08f0ef8acba0
Create Date: 2022-12-22 09:16:03.635294

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1712cc0ad50e'
down_revision = '08f0ef8acba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payment_analytics', ['payment_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_analytics', type_='unique')
    # ### end Alembic commands ###
