"""transaction

Revision ID: 1b06feae40b9
Revises: ab8b4b4cca90
Create Date: 2022-05-23 16:00:07.299832

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1b06feae40b9'
down_revision = 'ab8b4b4cca90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'customer_id')
    # ### end Alembic commands ###
