"""add_column_store_type_in_transaction

Revision ID: 2dec684fd385
Revises: 17f81b2050e9
Create Date: 2022-12-08 15:13:12.511683

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2dec684fd385'
down_revision = '17f81b2050e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('store_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'store_type')
    # ### end Alembic commands ###
