"""change in transaction db

Revision ID: 35c1544ced32
Revises: 91530800da4d
Create Date: 2022-07-25 16:39:16.197142

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35c1544ced32'
down_revision = '91530800da4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "request",
        new_column_name="api_request",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.alter_column(
        "transactions",
        "response",
        new_column_name="api_response",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.add_column('transactions', sa.Column('callback_request', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "api_request",
        new_column_name="request",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.alter_column(
        "transactions",
        "api_response",
        new_column_name="response",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.drop_column('transactions', 'callback_request')
    # ### end Alembic commands ###
