"""qr_codes

Revision ID: 6b28e9b4490b
Revises: 17f81b2050e9
Create Date: 2022-12-08 16:14:04.913011

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6b28e9b4490b'
down_revision = '17f81b2050e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qr_id', sqlmodel.sql.sqltypes.AutoString(length=65), nullable=False),
    sa.Column('is_fixed_amount', sa.SMALLINT(), nullable=True),
    sa.Column('usage', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('payment_amount', sa.Numeric(scale=2), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('api_request', sa.JSON(), nullable=True),
    sa.Column('api_response', sa.JSON(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=65), nullable=False),
    sa.Column('close_reason', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('driver', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('close_by', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
