"""add_info in refund

Revision ID: 91530800da4d
Revises: ab8b4b4cca90
Create Date: 2022-07-11 18:33:39.429046

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '91530800da4d'
down_revision = 'ab8b4b4cca90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund_transactions', sa.Column('additional_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund_transactions', 'additional_info')
    # ### end Alembic commands ###
