"""callbacks transaction change

Revision ID: 982b78d7f195
Revises: c9b9b7705a63
Create Date: 2022-08-22 13:51:43.053183

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '982b78d7f195'
down_revision = 'c9b9b7705a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_callbacks', 'event',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('transaction_callbacks', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_callbacks', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('transaction_callbacks', 'event',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
