"""transaction meta columns

Revision ID: a15f94f97c9f
Revises: 35c1544ced32
Create Date: 2022-07-25 20:11:32.327173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a15f94f97c9f'
down_revision = '35c1544ced32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refund_transactions",
        "request",
        new_column_name="api_request",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.alter_column(
        "refund_transactions",
        "response",
        new_column_name="api_response",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.alter_column(
        "transactions",
        "callback_request",
        new_column_name="callable_response",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.add_column('refund_transactions', sa.Column('api_status', mysql.TINYINT(), nullable=True))
    op.add_column('refund_transactions', sa.Column('callable_response', sa.JSON(), nullable=True))
    op.add_column('transactions', sa.Column('api_status', mysql.TINYINT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###\
    op.alter_column(
        "transactions",
        "callable_response",
        new_column_name="callback_request",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.alter_column(
        "refund_transactions",
        "api_request",
        new_column_name="request",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.alter_column(
        "refund_transactions",
        "api_response",
        new_column_name="response",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.drop_column('transactions', 'api_status')
    op.drop_column('refund_transactions', 'callable_response')
    op.drop_column('refund_transactions', 'api_status')

    # ### end Alembic commands ###
