"""payment_links

Revision ID: a39bce17d048
Revises: ae74981da483
Create Date: 2022-08-23 17:11:04.842432

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a39bce17d048'
down_revision = 'ae74981da483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('payment_links',
    #sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    #sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    #sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    #sa.Column('api_response', sa.JSON(), nullable=True),
    #sa.Column('update_count', sa.Integer(), nullable=False),
    #sa.Column('notify_sms_count', sa.Integer(), nullable=False),
    #sa.Column('notify_email_count', sa.Integer(), nullable=False),
    #sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    #sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    #sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    pass
    #sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    #sa.PrimaryKeyConstraint('id')
    #)
    #op.create_index('payment_link_comp_index', 'payment_links', ['transaction_id', 'invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('payment_link_comp_index', table_name='payment_links')
    op.drop_table('payment_links')
    # ### end Alembic commands ###
