"""transaction communication

Revision ID: ab8b4b4cca90
Revises: 669e8866a922
Create Date: 2022-05-20 13:35:29.988592

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ab8b4b4cca90'
down_revision = '669e8866a922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_communications', sa.Column('error', sa.TEXT(), nullable=True))
    op.add_column('transaction_communications', sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('transaction_communications', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_communications', 'status')
    op.drop_column('transaction_communications', 'event')
    op.drop_column('transaction_communications', 'error')
    # ### end Alembic commands ###
