"""transacton index

Revision ID: bf94b2604e74
Revises: 0343e864391f
Create Date: 2022-02-21 12:21:53.679660

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "bf94b2604e74"
down_revision = "0343e864391f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_transactions_gateway_order_id"),
        "transactions",
        ["gateway_order_id"],
        unique=False,
    )
    op.create_index(
        "transaction_comp_index",
        "transactions",
        ["source_id", "payment_type", "store_id", "client_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("transaction_comp_index", table_name="transactions")
    op.drop_index(op.f("ix_transactions_gateway_order_id"), table_name="transactions")
    # ### end Alembic commands ###
