"""transaction rmove cust id

Revision ID: d9011ec1ec18
Revises: 1b06feae40b9
Create Date: 2022-05-23 17:03:24.556000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9011ec1ec18'
down_revision = '1b06feae40b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('customer_id', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
