"""make qr_id and image_url nullable 

Revision ID: ddf82874c30e
Revises: 645ec701955a
Create Date: 2023-01-02 12:36:11.574339

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddf82874c30e'
down_revision = '645ec701955a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('access_points')
    # op.drop_table('access_client_relations')
    op.alter_column('qr_codes', 'qr_id',
               existing_type=mysql.VARCHAR(length=65),
               nullable=True)
    op.alter_column('qr_codes', 'image_url',
               existing_type=mysql.VARCHAR(length=65),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qr_codes', 'image_url',
               existing_type=mysql.VARCHAR(length=65),
               nullable=False)
    op.alter_column('qr_codes', 'qr_id',
               existing_type=mysql.VARCHAR(length=65),
               nullable=False)
    op.create_table('access_client_relations',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('endpoint_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='access_client_relations_ibfk_1'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['access_points.id'], name='access_client_relations_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('access_points',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('endpoint', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
