"""rabc and mis migrations

Revision ID: f76e23884123
Revises: 1712cc0ad50e
Create Date: 2023-01-10 12:42:06.820672

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f76e23884123'
down_revision = '1712cc0ad50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_points',
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_client_relations',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('endpoint_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['endpoint_id'], ['access_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('transaction_communications', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('transaction_communications', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_communications', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('transaction_communications', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.drop_table('access_client_relations')
    op.drop_table('access_points')
    # ### end Alembic commands ###
