"""transaction modification

Revision ID: fd394f160c79
Revises: 850585af2a1c
Create Date: 2022-02-14 18:12:49.329167

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "fd394f160c79"
down_revision = "850585af2a1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction_communications",
        sa.Column("transaction_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_constraint(
        "transaction_communications_ibfk_1",
        "transaction_communications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "transaction_communications", "transactions", ["transaction_id"], ["ulid"]
    )
    op.drop_column("transaction_communications", "transaction")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction_communications",
        sa.Column("transaction", mysql.VARCHAR(length=255), nullable=False),
    )
    op.drop_constraint(None, "transaction_communications", type_="foreignkey")
    op.create_foreign_key(
        "transaction_communications_ibfk_1",
        "transaction_communications",
        "transactions",
        ["transaction"],
        ["ulid"],
    )
    op.drop_column("transaction_communications", "transaction_id")
    # ### end Alembic commands ###
